### ISSUE TITLE
Directory `transaction` contains `responses`(Transaccion completa)

### ISSUE THREAD

**Issue by eugenioLopezRamos** [TransbankDevelopers/transbank-sdk-php#100]
In `transaccion_completa`, inside the `transaction` directory there are different kinds of `response`. This is good, but the directory should be named `responses`, both to better describe what it contains, and to keep consistency with the rest of the SDK. 
The composer.json also has to be modified to account for this renaming
Also, maybe other parts of the SDK have similar issues?

**Comment by gonzunigad** [comment]
This should be fixed on version 2.0 of tha package, when we stick to a single PSR-4 entrypoint on `src/` changing the namespace of all the clases.
