### ISSUE TITLE
Options class

### ISSUE THREAD

**Issue by iescaida** [TransbankDevelopers/transbank-sdk-php#103]
Options class should have a constructor for all the properties, which are commerceCode, Api key and integrationType
 
**Versiones (por favor agrega aquí la siguiente información):**
- SDK: transbank-sdk-php (Rest)
- PHP: 5.5+

**Comment by gonzunigad** [comment]
This PR should fulfill this issue: https://github.com/TransbankDevelopers/transbank-sdk-php/pull/139
