### ISSUE TITLE
TransbankDevelopers / transbank-sdk-php demo not workig 

### ISSUE THREAD

**Issue by jigarmurabiya** [TransbankDevelopers/transbank-sdk-php#114]
hello team ,

i have setup this demo on my server but i can not successfully run this demo with testing environment can you please help me to find issue 

Why do I keep getting connection timeout?
=> after submit token and redirect url getting connection timeout

please find below attachment for more information 

![Screenshot from 2020-01-31 12-05-55](https://user-images.githubusercontent.com/18063943/73518411-39f39e80-4424-11ea-95db-253b8a04a3d6.png)
![Screenshot from 2020-01-31 12-13-55](https://user-images.githubusercontent.com/18063943/73518412-39f39e80-4424-11ea-9cd0-5fc9bd6646cb.png)

let me know there is something missing in integration or step to run demo in test mode or primary requirement for running this demo

Thank you!!!

**Comment by AnilRamAhir** [comment]
yes i'm getting the same issue let me know if you find any solution?

**Comment by saengate** [comment]
Hello @AnilRamAhir @jigarmurabiya, this is not at error, some IP is blocked for security reasons. Please, contact to support through Slack to try help you.
https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by jigarmurabiya** [comment]
Solved Thank you!!!
