### ISSUE TITLE
Error en getTransactionResult por credenciales invalidas

### ISSUE THREAD

**Issue by wdevmaster** [TransbankDevelopers/transbank-sdk-php#129]
**Describe el bug**

Hola amigos de transbankdevelopers ten un pequeno problema integrando webpay normal en una api pero en la parte de donde uso el `getTransactionResult()` para obtener el resultado de la transaccion por lo que me da un error de credenciales aun cuando estoy usando las de prueba, he revisado la documetacion y el codigo del proyecto de ejemplo que tiene y aun asi se me presenta el mismo error.

Mi proyecto es API Rest relaizada en laravel 5.7 y usando el sdk de php, esta api recibe la solicitudes  para generar el proceso de pago y responde con los token he informacion corespondiente a los resultados, pero lo raro es que la credenciales de prueba me funciona para con el `initTransaction()`.

El workflow de mi proyecto es el siguiente:
- se envia una solicitud a la API `/payment/capture`
- se valida que haya la informacion para hacer el `initTransaction()`
- luego respondeo con el `token_ws` y `url`
- la web que recibe la respuesta de la API y hace la redirecion al proceso de pago de webpay
- al regresar al ruta del que se definion en `returnUrl`, se captura el token y se hace una solicitud a la API `/payment/get` enviandole el token.
- la ruta `/payment/get` intenta acceder al metodo `getTransactionResult()` y hay es cuando surge el error de credenciales.
 
**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 1.7
- PHP: 7.1
- LARAVEL: 5.7

**Comment by afiebig** [comment]
Hola @wdevmaster este error es común cuando la configuración del objeto no esta correcta. Favor revisar que al momento de hacer la llamada a `getTransactionResult` se esten configurando correctamente las credenciales ya sea de integración o producción.
