### ISSUE TITLE
Undefined class constant DEFAULT_MALL_COMMERCE_CODE

### ISSUE THREAD

**Issue by rpani** [TransbankDevelopers/transbank-sdk-php#145]
Estimados hay un error en el nombre de la constante utilizada la class WebpayPlus linea 113. 
Se está utilizando la constante DEFAULT_MALL_COMMERCE_CODE cuando debería ser DEFAULT_WEBPAY_PLUS_MALL_COMMERCE_CODE.

**Comment by gonzunigad** [comment]
Gracias por el reporte @rpani !

Este PR debe solcuonar el error: https://github.com/TransbankDevelopers/transbank-sdk-php/pull/148
