### ISSUE TITLE
Clases duplicadas

### ISSUE THREAD

**Issue by Fliik** [TransbankDevelopers/transbank-sdk-php#151]
Veo que se hizo un commit un cambio de nombre, pero a raíz de esto existe la carpeta Webpay y webpay, ambos con los mismos archivos, por favor corregir para saber cuales deben usarse.

**Comment by Fliik** [comment]
Lo mismo se repite con Patpass y patpass, Utils y utils, Onepay y onepay

**Comment by gonzunigad** [comment]
Tienes razón, ya está resuelto con los nuevos PR :)
