### ISSUE TITLE
Double slash in [capture] method

### ISSUE THREAD

**Issue by rquirola** [TransbankDevelopers/transbank-sdk-php#170]
Capture method not work.

This file contain an extra character
https://github.com/TransbankDevelopers/transbank-sdk-php/blob/master/src/Webpay/WebpayPlus/Transaction.php

Line27
`const CAPTURE_ENDPOINT = '/rswebpaytransaction/api/webpay/v1.0/transactions/$TOKEN$/capture';`

When concatenate the line, it looks like this:
`https://webpay3g.transbank.cl//rswebpaytransaction/api/webpay/v1.0/transactions/$TOKEN$/capture`

**This is the behavior on the user's site**

- in one client case the answer was 200 (OK)... but the transaction never appear in the transbank record.

- in other case the error was this:
`Error durante el cambio de estado. cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Solution**
Remove the slash before the word: rswebpaytransaction
`const CAPTURE_ENDPOINT = 'rswebpaytransaction/api/webpay/v1.0/transactions/$TOKEN$/capture';`

Thanks.

**Comment by gonzunigad** [comment]
Hola! Este PR debe solucionarlo: https://github.com/TransbankDevelopers/transbank-sdk-php/pull/172
¡Gracias por reportar!
