### ISSUE TITLE
[2.0] Agregar un Logger PSR-3

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#188]
**Problema**

El SDK no tiene ninguna forma de loggear transacciones, por lo que la interacción entre el SDK y los servidores de Transbank son completamente opacos a la aplicación, especialmente en desarrollo.

**Solución**

Incorporar un Logger PSR-3 a la instancia de Transbank.

Hacer que todos los servicios escriban en el log lo que envían (request, o similar) y lo que reciben (raw HTTP Response).

```php
public function create(...)
{
    $request = $this->createRequest(..);

    $this->log->debug('Sending request to Transbank', ['request' => $request]);

    $response = $this->httpClient->send($request);

    $this->log->debug('Received response from Transbank', ['request' => $request, 'response' => $response]);

    // ...
}
```

Si el Logger no es instanciado con Transbank, el SDK usará `NullLogger`.

## Breaking Changes

- Instanciar Transbank.

**Comment by gonzunigad** [comment]
Este me parece perfect.

**Comment by DarkGhostHunter** [comment]
La pega es meter el debug en todos los servicios y hacer que pasen los test. 😴

**Comment by gonzunigad** [comment]
Creoq ue bast meterlo en el [RequestService](https://github.com/TransbankDevelopers/transbank-sdk-php/blob/master/src/Utils/RequestService.php) nomás.

**Comment by DarkGhostHunter** [comment]
> Creoq ue bast meterlo en el [RequestService](https://github.com/TransbankDevelopers/transbank-sdk-php/blob/master/src/Utils/RequestService.php) nomás.

Cierto. Al menos que se sepa qué servicio está haciendo el request, asumiendo que hay comercios que usan más de uno.

**Comment by gonzunigad** [comment]
De todas formas, cada `APi Handler` (`WebpayPlus\Transaction`, etc) tiene un método `getLastRequest` y `getLastResponse`. 
También, si ocurre una excepción, estas tienen un objeto `request` para ver cual fue el request que falló. 

Sobre saber que producto falló, es interesante. Habría que ver una forma elegante de resolver eso.

**Comment by DarkGhostHunter** [comment]
> De todas formas, cada `APi Handler` (`WebpayPlus\Transaction`, etc) tiene un método `getLastRequest` y `getLastResponse`.

¿Esas reescriben la última, la añaden a la lista si, por ejemplo, hago siete?

> También, si ocurre una excepción, estas tienen una propiedad `request` (o algo así xD, no recuerdo el nombre) para ver cual fue el request que falló.

Lo importante es que, más que el request, se escriba en el log el `servicio.acción`.
 
> Sobre saber que producto falló, es interesante. Habría que ver una forma elegante de resolver eso.

```php
$this->log->debug(
    'Received response from Transbank', 
    [
        'service' => 'webpay.create',
        'request' => $request,
        'response' => $response
    ]
);
```

Tendría que recibirla la interfaz, si es que el log se empuja allí.

**Comment by gonzunigad** [comment]
> ¿Esas reescriben la última, la añaden a la lista si, por ejemplo, hago siete?

Si, reescriben. No es un historial 

> Lo importante es que, más que el request, se escriba en el log el servicio.acción.
Me gusta la idea. Solo ahbría que ver que clase recibe el logger y quién hace el debug, pero me gusta mucho la idea de agregar un logger. También me gustó lo de generar eventos :)

**Comment by mnavarrocarter** [comment]
Recomendaria que no metan el logger dentro de las clases. En vez de eso pueden usar el patron decorador y colocar el loger como una implementacion decorada del servicio.

**Comment by DarkGhostHunter** [comment]
> Recomendaria que no metan el logger dentro de las clases. En vez de eso pueden usar el patron decorador y colocar el loger como una implementacion decorada del servicio.

Se mete null logger si en el construct no se implementa manualmente.

**Comment by gonzunigad** [comment]
Creé algo así acá, pero le llamé VoidLogger: https://github.com/freshworkstudio/transbank-web-services/tree/master/src/Log

**Comment by DarkGhostHunter** [comment]
El PSR ya viene con un null logger. No hay que hacer nada. 

Italo Baeza C.

**Comment by gonzunigad** [comment]
UN PR acá es totalmente bienvenido :)

**Comment by mnavarrocarter** [comment]
> Se mete null logger si en el construct no se implementa manualmente.

Lo siento, no me expliqué muy bien. Introducir el logger en el constructor añade una responsabilidad más a la clase. No solo se comunica con transbank, pero tamben loggea la comunicacion.

Si tuvieramos una interfaz de puente entre las clases del SDK y clientes HTTP (como sugeri en #187), entonces podriamos hacer un decorador de ese `HttpClient` que tendria como unica responsabilidad el loggear lo que sucede.

Ejemplo:

```php
final class LoggerHttpService implements HttpService
{
    private HttpService $http;
    private LoggerInterface $logger;

    /**
     * LoggerService constructor.
     */
    public function __construct(HttpService $http, LoggerInterface $logger)
    {
        $this->http = $http;
        $this->logger = $logger;
    }

    /**
     * @throws ConnectionError
     * @throws ProtocolError
     */
    public function request(string $method, string $url, array $params = [], array $headers = []): array
    {
        $message = sprintf('Http Request: %s %s', $method, $url);
        $this->logger->debug($message, [
            'params' => $params,
            'headers' => $headers,
        ]);

        try {
            $data = $this->http->request($method, $url, $params, $headers);
        } catch (ConnectionError $e) {
            $this->logger->alert('Http Request Connection Error: '.$e->getMessage(), [
                'exception' => $e,
            ]);

            throw $e;
        } catch (ProtocolError $e) {
            $this->logger->critical('Http Request Protocol Error: '.$e->getMessage(), [
                'statusCode' => $e->getCode(),
                'exception' => $e,
            ]);

            throw $e;
        }
        $this->logger->debug('Http Request Successful', [
            'data' => $data,
        ]);

        return $data;
    }
}
```

Entonces, podemos envolver el `HttpService` de ejemplo en este. Y cualquier implementacion podria tener logging de esta forma.

**Comment by gonzunigad** [comment]
Si, suena bien! Hoy se ocupa HttpClientRequestService, que implemente Request Service. Quizás toca extender esa clase con LoggerRequestService

**Comment by mnavarrocarter** [comment]
Yo no usaria herencia. Es mucho mejor composicion.

**Comment by DarkGhostHunter** [comment]
_composition over inheritance_

**Comment by DarkGhostHunter** [comment]
Pero al instanciar la clase, igual se puede agregar NullLogger dentro de $loger. Si el dev no pasa un logger, no importa, se loguea nulo.

**Comment by mnavarrocarter** [comment]
Si, veo tu punto. Creo que a veces me pongo medio dogmatico con el SRP. No es tan malo el tener el Logger junto con la logica. Varias librerias lo hacen. 

Tradeoffs.

**Comment by gonzunigad** [comment]
Este issue me paree bueno y sería ideal agregar un Logger.  De momento no está dentro de las prioridades del equipo, por lo que es bienvenido un PR si alguien lo quiere tomar.
