### ISSUE TITLE
[2.0] Usar un objeto dinámico para respuestas de Transbank

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#189]
## Problema

Actualmente, para cada tipo de respuesta de Transbank, existe una clase que incorpora `getters`, en un intento de hacer la clase inmutable. Eso significa que si algún parámetro cambia en la respuesta a futuro, la clase se debe modificar.

## Solución

Hacer un único objeto dinámico, tentativamente llamado `TransbankResponse`, que permita inmutabilidad sin necesidad de crear una clase para cada tipo de respuesta, a la vez de incorporar el servicio y la acción que lo creó.

Hay un [ejemplo del código aquí](https://github.com/DarkGhostHunter/Transbank/blob/master/src/Services/Transactions/Transaction.php), pero en resumidas cuentas, se instancia metiendo el `array` de toda la respuesta, junto al servicio y acción que lo creó como `webpay.refund`.

```php
$response = new Transaction(`webpay.refund`, ['foo' => `bar`])

echo $response->foo; // "bar"

$response->foo = 'cougar';

echo $response->foo; // "bar"

echo $response->service_action; // "webpay.refund"
```

Esto se hace con la magia de `_get` y `_set`. También se puede usar `ArrayAccess` para permitir que los valores se pueda usar como `$response['foo']`. También permite que sea immutable.

Para objetos anidados, como `$response['card_details`]['card_number']`, devolvería el `array` tal cual:

```php
echo $response->card_details['card_number']; // "XXXXXXXXXXXX1234"
```

Con magia de `__call()` también se puede obtener cualquier valor usando `getFoo()`, pero lo veo innecesario si el objeto ya es immutable.

## Breaking Changes

- Getters
- Objeto a devolver en cada acción servicio sería el mismo, pero con datos diferentes.

**Comment by gonzunigad** [comment]
Hay otro beneficio importante, quizás más que la "inmutabilidad" y es los IDE reconocen automáticamente los métodos, lo que ayuda al integrador. Funciona mejor el autocomplete y te alerta si un método no existe o devuelve algo que no corresponde para lo que se está usando.

**Comment by DarkGhostHunter** [comment]
> Hay otro beneficio importante, quizás más que la "inmutabilidad" y es los IDE reconocen automáticamente los métodos, lo que ayuda al integrador. Funciona mejor el autocomplete y te alerta si un método no existe o devuelve algo que no corresponde para lo que se está usando.

Y si no tengo plata pal IDE? 😢 

Bueno, lo contrario sería crear una clase `Response` para cada tipo de respuesta, meter getters, y editarlos cada vez que la respuesta desde Transbank cambie en una nueva versión.

Había pensado en crear una clase abstracta dinámica, y usar PHPDoc en vez para cada respuesta, pero no todos los IDE entienden el PHPDoc:

```php
<?php

/**
 * @property-read string $foo
 */
class ResponseFoo extends BaseTransbankResponse
{
}
```

**Comment by gonzunigad** [comment]
> Y si no tengo plata pal IDE? 😢

Visual Studio Code con IntelliSense :)

> Bueno, lo contrario sería crear una clase Response para cada tipo de respuesta, meter getters, y editarlos cada vez que la respuesta desde Transbank cambie en una nueva versión.

Si una respuesta cambia en el API, toca hacer un nuevo major version del SDK y apuntar los métodos a la nueva versión. Eso tenemos medio decidido con el equipo. Cada major version del API es un major version en los SDK. Considerando esto, no creo que sea tanto problema cambiar el método de las clases que se hayan modificado. 

> Esto se hace con la magia de _get y _set. También se puede usar ArrayAccess para permitir que los valores se pueda usar como $response['foo']. También permite que sea immutable.

Esto me parece perfecto, intenté hacerlo, pero me faltó tiempo para entender porque no me funcionó nunca. Totalmente bienvenido.

**Comment by DarkGhostHunter** [comment]
> > Esto se hace con la magia de _get y _set. También se puede usar ArrayAccess para permitir que los valores se pueda usar como $response['foo']. También permite que sea immutable.
> 
> Esto me parece perfecto, intenté hacerlo, pero me faltó tiempo para entender porque no me funcionó nunca. Totalmente bienvenido.

Hay que encapsular la respuesta en un array interno, y luego implementar `ArrayAccess` sobre ese array. Lo mismo para `_get` y `_set`.

Ahora, usar un array interno sería mucho más fácil de implementar porque automágicamente te saltas tener que meter una nueva propiedad. Simplemente cada `getSomething()` saca el valor del array por su key. Si hay una nueva key desde el API, simplemente se añade o eliminar el getter().

Pero hey, añadir una propiedad sólo toma 2 segundos.

**Comment by mnavarrocarter** [comment]
No es un problema modificar una clase si el cambio es non-breaking: solo anadir una propiedad. Pero si el cambio es el renombramiento o eliminacion de un elemento del json de respuesta, entonces la api de transbank esta rompiendo el contrato y eso requeriria una nueva version de la implementacion.

Entonces, no creo que hay un real problema aqui.

**Comment by gonzunigad** [comment]
Si, el tema con getBuyOrder es que es camel case y la respuesta de Transbank es snake_case. Toca buscar alguna librería para hacer la conversión quizás, pero me suena a mucho, si es que ya me di la "lata" de crear todas las clases de respuesta (si, me demore su resto)

**Comment by DarkGhostHunter** [comment]
> Si, el tema con getBuyOrder es que es camel case y la respuesta de Transbank es snake_case. Toca buscar alguna librería para hacer la conversión quizás, pero me suena a mucho, si es que ya me di la "lata" de crear todas las clases de respuesta (si, me demore su resto)

Eso lo hice aquí. https://github.com/DarkGhostHunter/Transbank/blob/4ac57cc90b7a794d91dda86a35a31a75cba0b75c/src/Services/Transactions/DynamicallyAccess.php#L19

**Comment by DarkGhostHunter** [comment]
Bueno, creo que ya está dicho, se seguirán usando una clase para cada tipo de respuesta de Transbank.
