### ISSUE TITLE
[2.0] Separar Webpay de Webpay Mall

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#190]
## Problema

Actualmente Webpay Mall y Webpay, si bien son esencialmente el mismo servicio, no comparten las credenciales, la sintaxis y algunas respuesta son totalmente diferentes.

## Solución

Separar Webpay Mall y Webpay con sus propios servicios. Usando como base #186, podría invocarse como servicio aparte:

```php
$webpayTransaction = $transbank->webpay()->create(...);

$webpayMallTransaction = $transbank->webpayMall()->create(...);
```

## Breaking Changes

- Los métodos en `Webpay` para operaciones Mall se moverán a `WebpayMall`.

**Comment by gonzunigad** [comment]
Esto ya está separado. 

[Acá](https://github.com/TransbankDevelopers/transbank-sdk-php/tree/master/src/Webpay/WebpayPlus) puedes ver `Transaction` y `MallTransaction`. Cada uno por defecto define las credenciales por defecto, por lo que al un nuevo crear `MallTransaction` este usa por defecto las credenciales de Webpay Plus Mall Captura Simultánea.

**Comment by DarkGhostHunter** [comment]
Acknowledged

**Comment by gonzunigad** [comment]
Pulento.
