### ISSUE TITLE
Dependencia incompatible "satooshi/php-coveralls"

### ISSUE THREAD

**Issue by ffflabs** [TransbankDevelopers/transbank-sdk-php#195]
**TL/DR**

Quitemos la dependencia:

```bash
composer remove --dev satooshi/php-coveralls
```

**Describe el bug**

Se está requiriendo una dependencia no utilizada  `satooshi/php-coveralls` en el manifiesto de composer

https://github.com/TransbankDevelopers/transbank-sdk-php/blob/e30020931c6c5c30d02ac351191e4fba234d9be1/composer.json#L14

 
**Para reproducir**

1. Clonar una versión igual o anterior a la 2.0-beta e instalar sus dependencia con composer

```sh 
$ git clone git@github.com:TransbankDevelopers/transbank-sdk-php.git --depth=1 --branch=2.0-beta --single-branch  tbk-sdk-2.0-beta 
$ cd tbk-sdk-2.0-beta
$ composer install
```

2. Listar la info del paquete `satooshi/php-coveralls` (la salida del comando a continuación muestra solamente lo relevante)

```sh
$ composer info satooshi/php-coveralls

name     : satooshi/php-coveralls
...
names    : satooshi/php-coveralls
Attention: This package is abandoned and no longer maintained. The author suggests using the php-coveralls/php-coveralls package instead.

support

requires (dev)
phpunit/phpunit 3.7.*@stable
```

3. Listar quién está requiriendo el paquete `guzzle/guzzle` 

``` 
$ composer why guzzle/guzzle -t
  ...          
├──guzzle/guzzle v3.8.1 (replaces guzzle/batch self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/cache self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/common self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/http self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/inflection self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/iterator self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/log self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/parser self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-async self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-backoff self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-cache self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-cookie self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-curlauth self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-error-response self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-history self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-log self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-md5 self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-mock self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/plugin-oauth self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/service self.version) (circular dependency aborted here)
├──guzzle/guzzle v3.8.1 (replaces guzzle/stream self.version) (circular dependency aborted here)
└──satooshi/php-coveralls v0.6.1 (requires guzzle/guzzle >=3.0)
   └──transbank/transbank-sdk 2.0-beta (requires (for development) satooshi/php-coveralls ~0.6.1)
``` 

**Comportamiento observado**

- El plugin ya no se usa (no me consta si alguna vez se utilizó). Tampoco podría reactivarse dado que la última versión disponible en ese paquete soporta hasta PHPUnit 6. (Después se movió a[ php-coveralls/php-coveralls](https://packagist.org/packages/php-coveralls/php-coveralls))
- Instala la versión `3.8.1` de guzzle, que también gatilla la advertencia "this package is abandoned..."

**Comportamiento esperado**

No debiéramos mantener dependencias sin uso ni deprecadas. En general, tampoco instalar lo que no se use. En el futuro podemos usar algo como [composer-unused](https://github.com/composer-unused/composer-unused), pero no servirá para librerías viejas o que no cumplan con PSR-4

**Capturas de pantalla**

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.
![image](https://user-images.githubusercontent.com/238439/114409469-7c605180-9b78-11eb-8857-ec0cb33428f9.png)

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 2.0-beta
- PHP: 7.4.16

**Contexto adicional**

La dependencia es parte del `require-dev` por lo que no impacta en producción.

**Comment by gonzunigad** [comment]
Si, toda la razón, esa quedó ahí sin que enos demos cuenta. 
¿La elimino yo o haces tu un PR con eso para que quedes como contribuidor? :)

**Comment by gonzunigad** [comment]
Gracias por el PR. Con eso este issue debería quedar cerrado :)
