### ISSUE TITLE
Allow commerce to provide the ExternalUniqueNumber

### ISSUE THREAD

**Issue by afiebig** [TransbankDevelopers/transbank-sdk-php#20]
We have to allow the commerce to provide it's own `ExternelUniqueNumber` (`EUN`)

1- Overload Methods if necessary to maintain backwards compatibility.
2- Update the README to state that the commerce who provides its own `EUN` needs to guaranty its uniqueness inside the commerce.
3- Write Test.
4- Deploy a New Version.

**Comment by eugenioLopezRamos** [comment]
Added
