### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Transbank\Webpay\Webpay' not found in

### ISSUE THREAD

**Issue by Nemonikko** [TransbankDevelopers/transbank-sdk-php#205]
Estimado tengo ese error, 

Fatal error: Uncaught Error: Class 'Transbank\Webpay\Webpay' not found in /home/informatica/public_html/webpay/webpay.init.php:13 Stack trace: #0 {main} thrown in /home/informatica/public_html/webpay/webpay.init.php on line 13

mi código es el siguiente: https://www.informaticamedios.com/webpay/webpay.init.php

`
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);
error_reporting(E_ALL);

require_once '/home/informatica/vendor/autoload.php';

use Transbank\Webpay\Webpay;
use Transbank\Webpay\Configuration;

$transaction = (new Webpay(Configuration::forTestingWebpayPlusNormal()))
               ->getNormalTransaction();

$amount = 1000;
// Identificador que será retornado en el callback de resultado:
$sessionId = "1";
// Identificador único de orden de compra:
$buyOrder = "CODWARZONE";
$returnUrl = "https://www.informaticamedios.com/webpay/webpay.response.php";
$finalUrl = "https://www.informaticamedios.com/webpay/webpay.finish.php";

$initResult = $transaction->initTransaction(
    $amount, $sessionId, $buyOrder, $returnUrl, $finalUrl
);

$formAction = $initResult->url;
$tokenWs = $initResult->token;
`

la línea del error es: 

`$transaction = (new Webpay(Configuration::forTestingWebpayPlusNormal()))
               ->getNormalTransaction();`

tengo instalas las extensiones solicitadas, y la versión de php es 7.3.27 en CENTOS 7.9 kvm [vps-142879] v94.0.4, apache 4

pero me sigue tirando ese error.

**Comment by gonzunigad** [comment]
Hola @Nemonikko .
La version 2.X del SDK ya no tiene soporte para SOAP. 
 
 puedes usar la version 1.x, pero te recomendamos aprovechar de actualizar a la ultima version y usar el API REST.

**Comment by Nemonikko** [comment]
Estimado tienes el github de la última versión?

**Comment by gonzunigad** [comment]
Este es el github de la última versión. La versión 2.x es la última, la 1.x la anterior.
