### ISSUE TITLE
Librería no puede ser instalada usando PHP 7.0.33

### ISSUE THREAD

**Issue by mnavarrocarter** [TransbankDevelopers/transbank-sdk-php#212]
Hey @gonzunigad, estaba trabajando en la PR que prometi hace tiempo y me di cuenta que la libreria no puede ser instalada con PHP 7.0.
 
**Para reproducir**

1. Configura un contenedor con PHP 7.0.33, composer y las extensiones requeridas.
2. Ejecuta `composer install` dentro del contenedor
3. Se ve el error de dependencias en la consola

Tienes que asegurarte de tener `7.0`, debido a que este error no ocurre si estás haciendo install con, por ejemplo, un `7.3` que tienes en tu maquina local.

**Comportamiento observado**

El error de dependencias sucede debido a que esta libreria requiere `phpunit/phpunit ^9.0` y esa version de PHP Unit solo funciona con `7.3`. Tecnicamente, no hay usuarios afectados debido a que esta es una dependencia de desarrollo, pero si supone un problema cuando quieres desarrollar en 7.0.

**Comportamiento esperado**

Se espera que la libreria sea instalable con PHP 7.0 debido a que esa es la minima version soportada en `composer.json`.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/17072441/121174669-10d1f200-c852-11eb-9aac-15929f32f117.png)

**Versiones (por favor agrega aquí la siguiente información):**
- SDK:  2.0.3
- PHP: 7.0

**Contexto adicional**

La solucion propuesta es bajar a `phpunit/phpunit  ^8.5` y subir esta libreria a `^7.2`. Lo otro seria bajar a [`phpunit/phpunit ^6.5`](https://github.com/sebastianbergmann/phpunit/blob/6.5.14/composer.json) y ahi podriamos usarla sin problemas.

**Comment by gonzunigad** [comment]
Hola @mnavarrocarter . Instala el paquete con 'composer install --no-dev'. ¿Te funciona?

**Comment by mnavarrocarter** [comment]
Si, si funciona. Pero necesito phpunit para testear. 😄

**Comment by mnavarrocarter** [comment]
Hey @gonzunigad voy a hacer una PR bajando `phpunit/phpunit` a `^6.5`.

**Comment by gonzunigad** [comment]
Vale!, solo es importante que los tests que existen sigan operativos :)

**Comment by mnavarrocarter** [comment]
No te preocupes. Me hare cargo de eso.

**Comment by ffflabs** [comment]
@mnavarrocarter no creo que retroceder versiones sea la mejor solución, pero tienes un punto en que es relevante. Podría pasarse a producción un feature con sintaxis propia de php moderno.
    - name: Install PHP 7 dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
      if: "matrix.php >= 8"

```

no se podría probar correr los tests instalando con ` --ignore-platform-req` porque hay un montón de sintaxis en PHPUnit que no pasará las pruebas. Pero, para el caso, las mismas pruebas 



Si partimos de la base que la versión que instalarán los usuarios no cambia sin importar la solución de contingencia, entiendo que la disyuntiva está entre

    - Devolverse a una versión descontinuada de PHP, idem con PHPUnit,

**Comment by mnavarrocarter** [comment]
@ffflabs Pero tengo entendido que los chicos aca no pueden subir a 7.3, por ejemplo. Es asi aun @gonzunigad?

**Comment by gonzunigad** [comment]
Creo que puede ser mejor bajar la versión de PHPUnit, porque efectivamente nos ayudar´â a evitar escribir código que no sea compatible con PHP 7.0 y no darnos cuenta.
