### ISSUE TITLE
Error de tipeo en constante de TYPE de clase TransactionRefundResponse

### ISSUE THREAD

**Issue by prestaalba** [TransbankDevelopers/transbank-sdk-php#227]
**Describe el bug**

En la clase TransactionRefundResponse la constante:

const TYPE_NULLIFY = 'NULLIFY';

está incorrectamente definida. Lo correcto sería:

const TYPE_NULLIFIED = 'NULLIFIED';

Este error provoca que el método success() siempre retorne false para las transacciones de tipo NULLIFIED.

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 2.0.8
- PHP: 7.1

**Comment by gonzunigad** [comment]
Oops.

**Comment by mastudillot** [comment]
Solucionado, en la siguiente versión ya se encontrara incluido el fix 😄
