### ISSUE TITLE
Reembolso de transacción con errores siempre retorna código 422 en lugar del código especifico del intento de reembolso

### ISSUE THREAD

**Issue by prestaalba** [TransbankDevelopers/transbank-sdk-php#228]
**Describe el bug**

Al intentar hacer un reembolso de una transacción a través de Transaction.refund() y ocurrir un error, siempre retorna el código de error 422 genérico para las transacciones (El requerimiento no ha podido ser procesado ya sea por validaciones de datos o por lógica de negocios.) en lugar del código específico de los reembolsos.
 
**Para reproducir**

1. Crea una transacción y confírmala correctamente.
2. Intenta hacer un reembolso a dicha transacción por un monto superior al de la transacción.
3. Se lanza una excepción con el código de error 422.

**Comportamiento esperado**

En el caso anterior, debería retornar el código de error 311 (Monto a anular excede el saldo disponible para anular) de acuerdo a los códigos de errores posibles a retornar al intentar Reversar o Anular un pago de acuerdo a la documentación descrita en https://www.transbankdevelopers.cl/referencia/webpay#reversar-o-anular-un-pago

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: 2.0.8
- PHP: 7.1

**Comment by mastudillot** [comment]
Gracias por el reporte, vamos a revisar lo que mencionas

**Comment by mvarlic** [comment]
El api de Transbank ya no retorna el código de error, ahora la salida es: 

```
{
    "error_message": "Amount to refund is bigger than authorized"
}
```

no es un bug, ya que el sdk le da el mismo tratamiento que cualquier error que reciba, solo que ahora el api ya no retorna el código de error
