### ISSUE TITLE
Onepay should work in TEST out of the box (without setting credentials)

### ISSUE THREAD

**Issue by leosoto** [TransbankDevelopers/transbank-sdk-php#33]
The documentation (and the example project) spend some setting the right environment and credentials. But if we want people to start quickly, we shouldn't require them to set the credentials for the TEST environment. 

Therefore, we need to update this SDK (and the example project) to follow what we did on the Java side (see https://github.com/TransbankDevelopers/transbank-sdk-java/pull/40/ and https://github.com/TransbankDevelopers/transbank-sdk-java-onepay-example/pull/24/ )

**Comment by DarkGhostHunter** [comment]
Credentials should be added to this repository, but separately as a file instead of hardcoded into the classes.

**Comment by goncafa** [comment]
This issue is actually solved in release 1.4.0
