### ISSUE TITLE
Stance on PHP End of Life versions (5.6/7.0)

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#47]
For those who are not aware, [PHP 5.6 and PHP 7.0 will no longer maintained past this year](http://php.net/supported-versions.php) (the latter slightly before). The only ones actively maintained will be PHP 7.1 and PHP 7.2.

While that doesn't mean that they will become instantly insecure, no further security patches will be available.

Will this package be maintained to keep compatibility, or subsequent versions will require only PHP7.1+ (keeping the old but unmaintained)?

Asking because the package supports PHP 5.5, but it was gutted in 2016.

**Comment by leosoto** [comment]
We'd love to remove support for EOL'ed versions. But it's not an easy decision because there are some people running old software anyway. We need to gather some info on how many merchants are running those old versions to make an informed decision.

TL;DR: We don't know yet

**Comment by DarkGhostHunter** [comment]
Can I PR a note on the documentation about PHP EOL? LIke this:

> ### Note on older PHP versions:
> 
> We know that many merchants run unsupported PHP 5 and 7.0 versions. While it's always recommended to stay up-to-date for security reasons, a decision about deprecation won't be made until there is sufficient information about the impact it may have.

**Comment by LuisUrrutia** [comment]
I think that the issues #39 #45 and this one (#47) are too related.
The only incompatibility of Webpay SDK is the mcrypt usage and it will be removed #39 and everything should work... at least from the version 5.4.X of PHP.

I agree that we should drop the support for EOL'ed versions but it should be done with a "deprecation notice" through email and website (like the deprecation of KCC) and with enough time for developers to migrate their systems.

**Comment by goncafa** [comment]
We are currently working to make webpay sdk compatible with php 7+. You could see this work what is almost finished in the following active branch on this repo `feat/webpay-support-php7`

I have tested it on PHP 5.4 and PHP 7.2 so it will be compatible in both when we release it.

**Comment by DarkGhostHunter** [comment]
@goncafa Shouldn't be >5.5? At least, is what composer requires.

**Comment by goncafa** [comment]
You right @DarkGhostHunter mi mistake. PHP 5.5 and PHP 7.2

**Comment by DarkGhostHunter** [comment]
Just a reminder that PHP <= 5.6 and PHP <= 7.0 have died.

**Comment by DarkGhostHunter** [comment]
Yeah, apart from the big performance gaps and other very handy things exclusive for PHP 7.1 (Who said at least TooFewArgumentsException!?)

**Comment by WESV1980** [comment]
debí haber leido esto antes de instalar mi ambiente con la v7.3.6... :(

**Comment by DarkGhostHunter** [comment]
> debí haber leido esto antes de instalar mi ambiente con la v7.3.6... :(

Mi pésame hermano. 

Anyway, it seems that PHP 5.6 support won't be dropped anytime soon, at least, until the new "2.0" version of this SDK, which it seems is very far away.

**Comment by WESV1980** [comment]
En vez de avanzar con temas de desarrollo me he dedicado a realizar la creacion de ambientes a ciegas, creyendo que estaria disponible las librerias correspondientes, soy un noob en php pero he tenido que recurrir hasta aca debido a que no hay un SDK para .NETStandar 2.0, (bueno si lo hay pero para oneclick)... no se para que solicitan https en los endpoint si ni siquiera hay soporte para los principales lenguajes y actualizados... ahora voy a tener que invocar a don sata (downgrade php)... nos preocupamos de la pintura pero no del motor

**Comment by DarkGhostHunter** [comment]
> En vez de avanzar con temas de desarrollo me he dedicado a realizar la creacion de ambientes a ciegas, creyendo que estaria disponible las librerias correspondientes, soy un noob en php pero he tenido que recurrir hasta aca debido a que no hay un SDK para .NETStandar 2.0, (bueno si lo hay pero para oneclick)... no se para que solicitan https en los endpoint si ni siquiera hay soporte para los principales lenguajes y actualizados... ahora voy a tener que invocar a don sata (downgrade php)... nos preocupamos de la pintura pero no del motor

Pucha, Transbank indie developer. Te deseo suerte y que la deuda técnica sea sólo un par de líneas.

**Comment by WESV1980** [comment]
> Sí, aparte de las grandes brechas de rendimiento y otras cosas muy útiles exclusivas para PHP 7.1 (¿Quién dijo al menos TooFewArgumentsException?)

vi tu repo... se puede probar???

**Comment by DarkGhostHunter** [comment]
> > Sí, aparte de las grandes brechas de rendimiento y otras cosas muy útiles exclusivas para PHP 7.1 (¿Quién dijo al menos TooFewArgumentsException?)
> 
> vi tu repo... se puede probar???

No sé po... si querís. Adelante. También está la de [Freshwork](https://packagist.org/packages/freshwork/transbank) si quieres otras alternativas.

**Comment by WESV1980** [comment]
> > > Sí, aparte de las grandes brechas de rendimiento y otras cosas muy útiles exclusivas para PHP 7.1 (¿Quién dijo al menos TooFewArgumentsException?)
> > 
> > 
> > vi tu repo ... se puede probar ???
> 
> No sé po ... si querís. Adelante. También está la de [Freshwork](https://packagist.org/packages/freshwork/transbank) si quieres otras alternativas.

Estoy entregado... solo me guiare a tus recomendaciones... echare un vistazo

**Comment by WESV1980** [comment]
> > > Sí, aparte de las grandes brechas de rendimiento y otras cosas muy útiles exclusivas para PHP 7.1 (¿Quién dijo al menos TooFewArgumentsException?)
> > 
> > 
> > vi tu repo... se puede probar???
> 
> No sé po... si querís. Adelante. También está la de [Freshwork](https://packagist.org/packages/freshwork/transbank) si quieres otras alternativas.

De una!!! me resulto sin tener que hacer un downgrade de mi ambiente... de verdad muchas gracias.... saludos
