### ISSUE TITLE
Transbank Wrapper announcement

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#56]
I started working on the Wrapper. Gonna take me some good time, but the docs are up, and next up are the tests.

[You can view it here](https://github.com/DarkGhostHunter/transbank-wrapper/wiki).

It should be clear from the docs that a lot is made automatically and more expressively than using the SDK raw. A quick read on one of the operations should tell you what happens.

**Comment by DarkGhostHunter** [comment]
Finally I ended up doing the whole implementation myself.
https://github.com/DarkGhostHunter/TransbankApi

I think this should be the version 2.0. Since the public facing methods are detached from the implementation (adapter-client-transbank), you can change SOAP for REST easily. Look even how Onepay and Webpay work in tandem.

It also includes some very basic and verbose HTML examples to make integration transactions with dummy data.

**Comment by ffiebig** [comment]
Thanks for helping the Transbank community. As you know (but it's never wrong to mention it) you can help us improve sending us PRs and issues, they are always welcome.

I'm closing this just to keep things orderly
