### ISSUE TITLE
cant find lowercase files

### ISSUE THREAD

**Issue by Vagoasdf** [TransbankDevelopers/transbank-sdk-php#58]
In linux machines (at least Manjaro, Ubuntu and Debian ones), composer cant find the lowercase files when a Uppercase class is called. For example, when calling Transbank/Transbank/Webpay, the file does not exists, because its in webpay.php. 
In windows we dont have this problem because naming files in windows is case insenitive.
Renaming it to Webpay.php solves the issue

**Comment by ffiebig** [comment]
Thanks for reporting this, we'll be creating an issue in Jira to address this
