### ISSUE TITLE
Problems with the authorize OneClick method

### ISSUE THREAD

**Issue by AndresReyesTech** [TransbankDevelopers/transbank-sdk-php#66]
I am using the PHP SDK which works without problem when calling the InitInscription method, however, when wanting to authorize a payment with the previously received data, it drops indicating only a null value. 

I used another plugin (developed by Gonzalo de Freshwork and available on Github) and it gives me the same error but in that plugin I can activate a log. The exact problem is the following:

```
SoapFault {#236 ▼
  #message: "Authorization failed"
  #code: 0
  #file: "/Users/andres/Devel/oneclick.localhost/vendor/freshwork/transbank/src/TransbankWebService.php"
  #line: 136
  +"faultstring": "Authorization failed"
  +"faultcode": "soap:Server"
}
```
Attached log in case someone knows what can happen.

[TBKLOG.log](https://github.com/TransbankDevelopers/transbank-sdk-php/files/2745793/TBKLOG.log)

**Comment by AndresReyesTech** [comment]
Algún feedback?

**Comment by paulioceano** [comment]
Tengo exactamente el mismo problema.

Lograste dar con la solución?

**Comment by AndresReyesTech** [comment]
Hola @paulioceano,

Me comuniqué a soporte de Transbank y luego de muchos días (Casi 2 semanas) me respondieron que había un problema con la consulta lo cual no tiene sentido ya que usé el SDK y las consultas son  desarrolladas por ellos.

Sin embargo, comparto la respuesta de soporte:
_________________

Estimado buenas tardes:

Junto con saludar, le comparto la respuesta e nuestra área especialista a continuación:

Se realiza mismo flujo transaccional y el resultado fue exitosa, comercio debe revisar el usuario con el cual está invocando la autorización asociado al tbk_user. :

Request

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://webservices.webpayserver.transbank.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:authorize>
         <arg0>
            <amount>10000000</amount>
            <buyOrder>20190111015123</buyOrder>
            <tbkUser>8c194e6a-50f4-4464-add1-46cef2a687cd</tbkUser>
            <username>maldo</username>
         </arg0>
      </web:authorize>
   </soapenv:Body>
</soapenv:Envelope>
```

Response

```
<soap:Body wsu:Id="id-17059" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
      <ns2:authorizeResponse xmlns:ns2="http://webservices.webpayserver.transbank.com/">
         <return>
            <authorizationCode>1213</authorizationCode>
            <creditCardType>Visa</creditCardType>
            <last4CardDigits>6623</last4CardDigits>
            <responseCode>0</responseCode>
            <transactionId>13112803</transactionId>
         </return>
      </ns2:authorizeResponse>
   </soap:Body>
</soap:Envelope>
```

Además le comparto las credenciales para el ambiente de integración y que nos percatamos que están ocupando las credenciales antiguas:

One Click Normal 597044444405

https://drive.google.com/drive/folders/1GpkaE9DzvZ70tEASHI3o1wYzAiFP9jTb?usp=sharing
_________________

Ojo: si te das cuenta en el log el tbkUser que usé es correcto y por lo mismo para mi problema la solución no pasa por eso. Finalmente no seguí avanzando en el desarrollo porque mi cliente desistió de OneClick en favor de PayPal.

Ojalá te sirva de algo la respuesta.
