### ISSUE TITLE
The api doc for the initTransaction call it's wrong

### ISSUE THREAD

**Issue by gustavonecore** [TransbankDevelopers/transbank-sdk-php#67]
I have faced a weird issue calling the initTransaction method.
From the docs: [create transaction](https://www.transbankdevelopers.cl/referencia/webpay#crear-una-transaccion-webpay-plus-normal)

The order of args are: `$amount, $sessionId, $buyOrder, $returnUrl, $finalUrl`
But the code already have: 

```
    public function initTransaction($amount, $buyOrder, $sessionId, $urlReturn, $urlFinal)
    {
```

So, if you try to use something like an uuidv5 for the session it would not work, since that arg it's related to the session id.

**Comment by ffiebig** [comment]
Hi @gustavonecore you're right, we'll fix this as soon as we can, we'll create an issue in Jira

**Comment by a1b4** [comment]
The documentation was fixed, thank you @gustavonecore for this issue
